// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbptxapqzauukmzrhfaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicHR4YXBxemF1dWttenJoZmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzMzMzAsImV4cCI6MjA2MDYwOTMzMH0.wE7srxeS4gj9l7fx280uUXx73dek8HU0T_CMg5aO9Sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);